services:
  gz:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
      # args:
      #   - BASE_IMAGE=gz11-gz:latest
    user: "user"
    volumes:
      - .:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /dev/dri:/dev/dri 
      - /dev/nvidia0:/dev/nvidia0 
      - /dev/nvidiactl:/dev/nvidiactl 
      - /dev/nvidia-modeset:/dev/nvidia-modeset 
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    hostname: g11
    extra_hosts:
      - "g11:127.0.0.1"
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
      # - __NV_PRIME_RENDER_OFFLOAD=1
      # - __GLX_VENDOR_LIBRARY_NAME=nvidia
    runtime: nvidia